// PRODUCT DATABASE (CUSTOM BARCODES)
const productEcoDB = {
  "111111111111": { name: "Plastic Spoon", score: 30 },
  "222222222222": { name: "Paper Cup", score: 70 },
  "333333333333": { name: "Glass Bowl", score: 85 },
  "444444444444": { name: "Metal Plate", score: 90 },
  "555555555555": { name: "Cardboard Box", score: 75 }
};

// 50 ECO QUIZ QUESTIONS
const quizQuestions = [
  { q: "Plastic takes hundreds of years to decompose.", a: true },
  { q: "Glass can be recycled infinitely.", a: true },
  { q: "Paper is not recyclable.", a: false },
  { q: "Metal recycling saves energy.", a: true },
  { q: "Food waste releases methane gas.", a: true },
  { q: "Turning off lights saves energy.", a: true },
  { q: "Plastic bags are eco-friendly.", a: false },
  { q: "E-waste contains toxic materials.", a: true },
  { q: "Composting reduces landfill waste.", a: true },
  { q: "Renewable energy comes from fossil fuels.", a: false },
  { q: "LED bulbs use less electricity.", a: true },
  { q: "Water conservation saves energy.", a: true },
  { q: "Single-use plastics are sustainable.", a: false },
  { q: "Planting trees helps fight climate change.", a: true },
  { q: "Fast fashion increases pollution.", a: true },
  { q: "Recycling saves natural resources.", a: true },
  { q: "Plastic bottles are made from plants.", a: false },
  { q: "Public transport reduces emissions.", a: true },
  { q: "Oceans absorb CO₂.", a: true },
  { q: "Eco products are always expensive.", a: false },
  { q: "Solar panels work at night.", a: false },
  { q: "Reducing waste helps the environment.", a: true },
  { q: "Bamboo is sustainable.", a: true },
  { q: "Plastic straws harm marine life.", a: true },
  { q: "Buying local reduces emissions.", a: true },
  { q: "Deforestation affects rainfall.", a: true },
  { q: "Electric vehicles have zero lifetime emissions.", a: false },
  { q: "Food miles impact climate change.", a: true },
  { q: "Reusable bottles reduce waste.", a: true },
  { q: "Recycling paper saves trees.", a: true },
  { q: "Plastic pollution affects health.", a: true },
  { q: "Wind energy is non-renewable.", a: false },
  { q: "Eco labels help consumers.", a: true },
  { q: "Burning waste is eco-friendly.", a: false },
  { q: "Water scarcity is global.", a: true },
  { q: "Biodegradable means instant decay.", a: false },
  { q: "Saving water saves electricity.", a: true },
  { q: "Climate change affects wildlife.", a: true },
  { q: "Plastic recycling rate is 100%.", a: false },
  { q: "Air pollution harms health.", a: true },
  { q: "Sustainability is long-term thinking.", a: true },
  { q: "Throwing waste in rivers is safe.", a: false },
  { q: "Energy-efficient appliances save power.", a: true },
  { q: "Climate change is only future issue.", a: false },
  { q: "Plant-based diets reduce emissions.", a: true },
  { q: "Recycling alone solves pollution.", a: false }
];
